version: 0.0
os: linux
files:
  - source: /shell_scripts
    destination: /home/ec2-user/airflow-repository/shell_scripts

    

hooks:
  AfterInstall:
    - location: deploy_hooks/make_shells_executable.sh