version: 0.0
os: linux
files:
  - source: /dags
    destination: /home/ec2-user/airflow/dags
  - source: /Shells
    destination: /home/ec2-user/airflow-repository/Shells
  - source: /SQL_Scripts
    destination: /home/ec2-user/airflow-repository/SQL_Scripts