
version: 0.0
os: linux
files:
  - source: /dags
    destination: /home/airflow/airflow/dags
  - source: /jobs
    destination: /home/airflow/airflow-repository/jobs

hooks:
  AfterInstall:
    - location: deployment/hooks/make_shells_executable.sh